import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./component/navbar/page";
// import ZustandFile from "./component/zustand";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-200">
        <Sidebar/>
        <div className="ml-[150px] p-6  pt-12">
        {children}
        </div>
        </body>
    </html>
  );
}
